In [3]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? 
    If there is then write a code to print the data types of both the variables.

Ans-

The main difference between the data types of list_ and array_list is that list_ is a Python list, which can contain elements of different data types, 
whereas array_list is a NumPy array that can only contain elements of a single data type.

In the given code, the list_ variable contains string elements, but it could contain elements of any data type, such as integers, floats, booleans, or even other nested lists. 
On the other hand, the array_list variable is created using NumPy array() function, which by default converts all elements of the input object to a common data type. 
In this case, the string elements of list_ are converted to the string data type in the resulting NumPy array array_list.

Using a NumPy array with a single data type has several advantages over using a Python list with mixed data types, including faster computation speed, lower memory usage, and better support for mathematical operations.

In [4]:
#Print the data types:

print(type(list_))       
print(type(array_list)) 

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

#Ans-

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element of list_
for element in list_:
    print(type(element))

# Print data type of each element of array_list
for element in array_list:
    print(element.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


In [ ]:
Q3. Considering the following changes in the variable, array_list:
    array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 
If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Ans-

Yes, there will be a difference in the data type of the elements present in list_ and array_list. 
When creating array_list using the np.array() function and specifying the dtype argument as int, all elements of the original list_ will be converted to integers as we are specifying the dtype=int.


In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element of list_
for element in list_:
    print(type(element))

# Print data type of each element of array_list
for element in array_list:
    print(element.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64
int64
int64
int64
int64


In [7]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
#(i) Find the shape of the array
shape = num_array.shape
print("Shape of the array:", shape)

Shape of the array: (2, 3)


In [9]:
# (ii) Find the size of the array
size = num_array.size
print("Size of the array:", size)

Size of the array: 6


In [10]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy arraycreation function.
 #   [Hint: The size of the array will be 9 and the shape will be (3,3).]
    
#Ans-

# Create a numpy array of zeros with a shape of (3, 3)
zeros_array = np.zeros(shape=(3, 3))

# Print the zeros array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
    #[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

#Ans-

# Create a 5x5 identity matrix
identity_matrix = np.identity(n=5)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
